name: Build Windows App on Release

on:
  release:
    types: [published]
    repository: advplyr/audiobookshelf

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: advplyr/audiobookshelf
          ref: ${{ github.event.release.tag_name }}
          path: ./audiobookshelf  # Checkout into this directory

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ./audiobookshelf

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build Windows app
        run: npm run build-win
        working-directory: ./audiobookshelf
