name: Build Windows installer on Release of audiobookshelf

on:
  release:
    types: [published]
    repository: advplyr/audiobookshelf
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Test Inno Setup
      - name: Test Inno Setup
        run: iscc /?
        
      # 1. Build the audiobookshelf executable
      - uses: actions/checkout@v3
        with:
          repository: advplyr/audiobookshelf
          ref: ${{ github.event.release.tag_name }}
          path: ./audiobookshelf  # Checkout into this directory

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ./audiobookshelf

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build windows executable
        run: npm run build-win
        working-directory: ./audiobookshelf

      # 2. Build the tray app
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Build solution
        run: dotnet build -c Release
