name: Crete test release

on:
  workflow_dispatch:

jobs:
  create-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test_tag
          release_name: test_release
          draft: false
          prerelease: true
