name: Get Latest Audiobookshelf Release

on:
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getLatestRelease({
              owner: 'advplyr',
              repo: 'audiobookshelf',
            })
            console.log(data.tag_name)
            console.log(context)